baseURL: ""
languageCode: en-us
title: Andrea Knápková
theme: "PaperMod"
paginate: 5



enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Andrea Knápková
  description: "Vítejte v Ateliéru klidu a radosti"
  keywords: [Blog, Portfolio, PaperMod]
  author: 
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false
  disableAnchoredHeadings: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/logo.svg"
    favicon16x16: "/logo.svg"
    favicon32x32: "/logo.svg"
    apple_touch_icon: "/logo.svg"
    safari_pinned_tab: "/logo.svg"

  label:
    text: "Andrea Knápková"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Vítejte v Ateliéru klidu a radosti
    subtitle: ">Mým cílem je ukázat člověku, že je mnohem komfortnější být v roli tvůrce, nežli oběti. A žít šťastný, zdravý, spokojený, vyrovnaný život nehledě na okolnostech a vnějších vlivech z okolí."
    imageUrl: "/logo.svg"
    imageWidth: 800
    imageHeight: 300
    
    

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: "email"
      url: "mailto:info@andreaknapkova.cz"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page


  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: omne
      name: O mně
      url: /o-mne/
      weight: 10
    - identifier: metoda
      name: Metoda
      url: /metoda/
      weight: 20
    - identifier: terapie
      name: Terapie
      url: /terapie/
      weight: 30
    - identifier: kontakt
      name: Kontakt
      url: /kontakt/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: false
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai